# -*- coding: utf-8 -*-
"""HT6411_10 สาริน ขุนจันทร์.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ay6CAVpt2Ixz8yMTTejO3Q9ypQDyVrWp
"""

print("ถ้าคะแนนมากกว่าหรือเท่ากับ 80 คะแนนจะได้ A \nถ้าคะแนนเท่ากับ 70-79 คะแนนจะได้ B \nถ้าคะแนนเท่ากับ 60-69 คะแนนจะได้ C \nถ้าคะแนนเท่ากับ 50-59 คะแนนจะได้ D ")
print("ถ้าคะแนนน้อยกว่า 50 เกรดจะเป็น F โดยอัตโนมัติ")
mark = int(input("please enter your mark : "))
print("-------------------------------------")

if (mark >= 0 and mark <= 100):
 if mark >= 80:
    def sum_function():
     grade = 'A'
     print(f'คะแนนของคุณคือ {mark} \nเกรดของคุณคือ {grade}')
 elif mark > 69:
   def sum_function():
     grade = 'B'
     print(f'คะแนนของคุณคือ {mark} \nเกรดของคุณคือ {grade}')
 elif mark > 59:
   def sum_function():
     grade = 'C'
     print(f'คะแนนของคุณคือ {mark} \nเกรดของคุณคือ {grade}')
 elif mark >= 50:
   def sum_function():
     grade = 'D'
     print(f'คะแนนของคุณคือ {mark} \nเกรดของคุณคือ {grade}')
 else :
   def sum_function():
     grade = 'F'
     print(f'คะแนนของคุณคือ {mark} \nเกรดของคุณคือ {grade}')
else:
  def sum_function():
     print(f'ระบบนี้ใส่ได้เฉพาะคะแนน 1-100 ครับ')

sum_function()
#HT6411_10 สาริน ขุนจันทร์